package com.cafebabe;

import com.cafebabe.entity.phone.Phone;

import java.io.File;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface Phones {

    Phone REDMI_9_3GB_32GB_GLOBAL_WITH_NFC_GREEN = new Phone(
            "REDMI_9_3GB_32GB_GLOBAL_WITH_NFC_GREEN",
            3f,
            32f,
            Manufacturers.XIAOMI,
            2020,
            OperationSystems.ANDROID_TEN_DOT_ZERO,
            6.53f,
            1080,
            2340,
            ScreenTechnologies.IPS,
            60,
            FingerprintScannerLocations.ON_THE_BACK_PANEL,
            2,
            SimCardTypes.NANO_SIM,
            true,
            4,
            13,
            false,
            PhoneCpus.MEDIATEK_HELIO_G80,
            8,
            true,
            ConnectionSockets.USB_TYPE_C,
            Colors.GREEN,
            null,
            163.3f,
            77f,
            9.1f,
            198f,
            5020,
            ScreenProtections.GORILLA_GLASS_V3,
            true
    ), REDMI_9_4GB_64GB_GLOBAL_WITH_NFC_PURPLE = new Phone(
            "REDMI_9_4GB_64GB_GLOBAL_WITH_NFC_PURPLE",
            4f,
            64f,
            Manufacturers.XIAOMI,
            2020,
            OperationSystems.ANDROID_TEN_DOT_ZERO,
            6.53f,
            1080,
            2340,
            ScreenTechnologies.IPS,
            60,
            FingerprintScannerLocations.ON_THE_BACK_PANEL,
            2,
            SimCardTypes.NANO_SIM,
            true,
            4,
            13,
            false,
            PhoneCpus.MEDIATEK_HELIO_G80,
            8,
            true,
            ConnectionSockets.USB_TYPE_C,
            Colors.PURPLE,
            null,
            163.3f,
            77f,
            9.1f,
            198f,
            5020,
            ScreenProtections.GORILLA_GLASS_V3,
            true
    ), REDMI_9C_2GB_32GB_GLOBAL_ORANGE = new Phone(
            "REDMI_9C_2GB_32GB_GLOBAL_ORANGE",
            2f,
            32f,
            Manufacturers.XIAOMI,
            2020,
            OperationSystems.ANDROID_TEN_DOT_ZERO,
            6.53f,
            720,
            1600,
            ScreenTechnologies.IPS,
            60,
            FingerprintScannerLocations.ON_THE_BACK_PANEL,
            2,
            SimCardTypes.NANO_SIM,
            true,
            3,
            13,
            false,
            PhoneCpus.MEDIATEK_HELIO_G35,
            5,
            true,
            ConnectionSockets.MICRO_USB,
            Colors.ORANGE,
            null,
            164.9f,
            77.07f,
            9f,
            196f,
            5000,
            null,
            false
    ), REDMI_9C_3GB_64GB_GLOBAL_GRAY = new Phone(
            "REDMI_9C_3GB_64GB_GLOBAL_GREY",
            3f,
            64f,
            Manufacturers.XIAOMI,
            2020,
            OperationSystems.ANDROID_TEN_DOT_ZERO,
            6.53f,
            720,
            1600,
            ScreenTechnologies.IPS,
            60,
            FingerprintScannerLocations.ON_THE_BACK_PANEL,
            2,
            SimCardTypes.NANO_SIM,
            true,
            3,
            13,
            false,
            PhoneCpus.MEDIATEK_HELIO_G35,
            5,
            true,
            ConnectionSockets.MICRO_USB,
            Colors.GREY,
            null,
            164.9f,
            77.07f,
            9f,
            196f,
            5000,
            null,
            false
    ), REDMI_9C_4GB_64GB_GLOBAL_BLUE = new Phone(
            "REDMI_9C_4GB_64GB_GLOBAL_BLUE",
            4f,
            64f,
            Manufacturers.XIAOMI,
            2020,
            OperationSystems.ANDROID_TEN_DOT_ZERO,
            6.53f,
            720,
            1600,
            ScreenTechnologies.IPS,
            60,
            FingerprintScannerLocations.ON_THE_BACK_PANEL,
            2,
            SimCardTypes.NANO_SIM,
            true,
            3,
            13,
            false,
            PhoneCpus.MEDIATEK_HELIO_G35,
            5,
            true,
            ConnectionSockets.MICRO_USB,
            Colors.BLUE,
            null,
            164.9f,
            77.07f,
            9f,
            196f,
            5000,
            null,
            false
    ), XIAOMI_REDMI_NOTE_9T_4GB_64GB_GLOBAL_BLACK = new Phone(
            "XIAOMI_REDMI_NOTE_9T_4GB_64GB_GLOBAL_BLACK",
            4f,
            64f,
            Manufacturers.XIAOMI,
            2021,
            OperationSystems.ANDROID_TEN_DOT_ZERO,
            6.53f,
            1080,
            2340,
            ScreenTechnologies.IPS,
            60,
            FingerprintScannerLocations.ON_THE_SIDE_END,
            2,
            SimCardTypes.NANO_SIM,
            true,
            3,
            48,
            true,
            PhoneCpus.MEDIATEK_DIMENSITY_800,
            13,
            true,
            ConnectionSockets.USB_TYPE_C,
            Colors.BLACK,
            null,
            161.9f,
            77.3f,
            9.05f,
            199f,
            5000,
            ScreenProtections.GORILLA_GLASS_V5,
            true
    ), XIAOMI_REDMI_NOTE_9T_4GB_128GB_GLOBAL_PURPLE = new Phone(
            "XIAOMI_REDMI_NOTE_9T_4GB_128GB_GLOBAL_PURPLE",
            4f,
            128f,
            Manufacturers.XIAOMI,
            2021,
            OperationSystems.ANDROID_TEN_DOT_ZERO,
            6.53f,
            1080,
            2340,
            ScreenTechnologies.IPS,
            60,
            FingerprintScannerLocations.ON_THE_SIDE_END,
            2,
            SimCardTypes.NANO_SIM,
            true,
            3,
            48,
            true,
            PhoneCpus.MEDIATEK_DIMENSITY_800,
            13,
            true,
            ConnectionSockets.USB_TYPE_C,
            Colors.PURPLE,
            null,
            161.9f,
            77.3f,
            9.05f,
            199f,
            5000,
            ScreenProtections.GORILLA_GLASS_V5,
            true
    ), POCO_X3_PRO_GLOBAL_6GB_128GB_BLACK = new Phone(
            "POCO_X3_PRO_GLOBAL_6GB_128GB_BLACK",
            6f,
            128f,
            Manufacturers.XIAOMI,
            2021,
            OperationSystems.ANDROID_ELEVEN,
            6.67f,
            1080,
            2400,
            ScreenTechnologies.IPS,
            120,
            FingerprintScannerLocations.ON_THE_SIDE_END,
            2,
            SimCardTypes.NANO_SIM,
            true,
            4,
            48,
            false,
            PhoneCpus.QUALCOMM_SNAPDRAGON_860,
            20,
            true,
            ConnectionSockets.USB_TYPE_C,
            Colors.BLACK,
            DustAndMoistureProtectionTypes.IP53,
            165.3f,
            76.8f,
            9.4f,
            215f,
            5160,
            ScreenProtections.GORILLA_GLASS_V6,
            true
    ), POCO_X3_PRO_GLOBAL_8GB_256GB_BRONZE = new Phone(
            "POCO_X3_PRO_GLOBAL_8GB_256GB_BRONZE",
            8f,
            256f,
            Manufacturers.XIAOMI,
            2021,
            OperationSystems.ANDROID_ELEVEN,
            6.67f,
            1080,
            2400,
            ScreenTechnologies.IPS,
            120,
            FingerprintScannerLocations.ON_THE_SIDE_END,
            2,
            SimCardTypes.NANO_SIM,
            true,
            4,
            48,
            false,
            PhoneCpus.QUALCOMM_SNAPDRAGON_860,
            20,
            true,
            ConnectionSockets.USB_TYPE_C,
            Colors.BRONZE,
            DustAndMoistureProtectionTypes.IP53,
            165.3f,
            76.8f,
            9.4f,
            215f,
            5160,
            ScreenProtections.GORILLA_GLASS_V6,
            true
    );

    List<Phone> ALL = Arrays.asList(POCO_X3_PRO_GLOBAL_8GB_256GB_BRONZE, POCO_X3_PRO_GLOBAL_6GB_128GB_BLACK, XIAOMI_REDMI_NOTE_9T_4GB_128GB_GLOBAL_PURPLE, XIAOMI_REDMI_NOTE_9T_4GB_64GB_GLOBAL_BLACK, REDMI_9C_4GB_64GB_GLOBAL_BLUE, REDMI_9C_3GB_64GB_GLOBAL_GRAY, REDMI_9C_2GB_32GB_GLOBAL_ORANGE, REDMI_9_4GB_64GB_GLOBAL_WITH_NFC_PURPLE, REDMI_9_3GB_32GB_GLOBAL_WITH_NFC_GREEN);

    Map<Phone, String> PHONE_TO_IMAGES_DIRECTORY_MAP = new HashMap<Phone, String>() {{
        put(POCO_X3_PRO_GLOBAL_8GB_256GB_BRONZE, "poco_x3_pro" + File.separator + "poco_x3_pro_bronze");
        put(POCO_X3_PRO_GLOBAL_6GB_128GB_BLACK, "poco_x3_pro" + File.separator + "poco_x3_pro_black");
        put(XIAOMI_REDMI_NOTE_9T_4GB_128GB_GLOBAL_PURPLE, "redmi_note_9t" + File.separator + "redmi_note_9t_purple");
        put(XIAOMI_REDMI_NOTE_9T_4GB_64GB_GLOBAL_BLACK, "redmi_note_9t" + File.separator + "redmi_note_9t_black");
        put(REDMI_9C_4GB_64GB_GLOBAL_BLUE, "redmi_9c" + File.separator + "redmi_9c_blue");
        put(REDMI_9C_3GB_64GB_GLOBAL_GRAY, "redmi_9c" + File.separator + "redmi_9c_gray");
        put(REDMI_9C_2GB_32GB_GLOBAL_ORANGE, "redmi_9c" + File.separator + "redmi_9c_orange");
        put(REDMI_9_4GB_64GB_GLOBAL_WITH_NFC_PURPLE, "redmi_9" + File.separator + "redmi_9_purple");
        put(REDMI_9_3GB_32GB_GLOBAL_WITH_NFC_GREEN, "redmi_9" + File.separator + "redmi_9_green");
    }};
}
