package com.cafebabe.service.impl;

import com.cafebabe.entity.FingerprintScannerLocation;
import com.cafebabe.repository.FingerprintScannerLocationRepository;
import com.cafebabe.service.interfaces.FingerprintScannerLocationService;
import org.springframework.stereotype.Service;

@Service
public class FingerprintScannerLocationServiceImpl extends BaseDataObjectWithUniqueNameServiceImpl<FingerprintScannerLocationRepository, FingerprintScannerLocation> implements FingerprintScannerLocationService {
}
